#!/usr/bin/env bash
# =============================================================================
# setup-session.sh - Create session directory structure
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

# =============================================================================
# MAIN FUNCTIONS
# =============================================================================

create_session_directory() {
    local session_id="$1"

    local session_dir
    session_dir=$(get_session_dir "$session_id")

    if [[ -d "$session_dir" ]]; then
        log_warning "Session directory already exists: $session_dir"
        return 0
    fi

    log_info "Creating session directory: $session_dir"
    mkdir -p "$session_dir"

    log_success "Created: $session_dir"
}

create_placeholder_files() {
    local session_id="$1"

    local session_dir
    session_dir=$(get_session_dir "$session_id")

    # Create placeholder spec.md if not exists
    if [[ ! -f "$session_dir/spec.md" ]]; then
        cat > "$session_dir/spec.md" << EOF
# Session Specification

**Session ID**: \`$session_id\`
**Status**: Not Started
**Created**: $(get_date)

---

## Placeholder

This specification will be generated by /sessionspec command.
EOF
        log_info "Created placeholder: spec.md"
    fi
}

update_state() {
    local session_id="$1"

    log_info "Updating state.json..."
    set_current_session "$session_id"
    log_success "Current session set to: $session_id"
}

# =============================================================================
# USAGE
# =============================================================================

show_usage() {
    cat << EOF
Usage: $(basename "$0") SESSION_ID [OPTIONS]

Create session directory structure.

ARGUMENTS:
  SESSION_ID    Session identifier (e.g., phase01-session03-auth)

OPTIONS:
  -p, --placeholder   Create placeholder files
  -u, --update-state  Update state.json with current session
  -h, --help          Show this help message

EXAMPLES:
  $(basename "$0") phase01-session03-auth
  $(basename "$0") phase01-session03-auth --update-state
  $(basename "$0") phase00-session01-setup -p -u
EOF
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    local session_id=""
    local create_placeholders=false
    local update_state_flag=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            -p|--placeholder)
                create_placeholders=true
                shift
                ;;
            -u|--update-state)
                update_state_flag=true
                shift
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            -*)
                log_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
            *)
                if [[ -z "$session_id" ]]; then
                    session_id="$1"
                else
                    log_error "Multiple session IDs provided"
                    show_usage
                    exit 1
                fi
                shift
                ;;
        esac
    done

    if [[ -z "$session_id" ]]; then
        log_error "Session ID required"
        show_usage
        exit 1
    fi

    # Validate session ID format
    if ! parse_session_id "$session_id" > /dev/null 2>&1; then
        log_error "Invalid session ID format: $session_id"
        log_info "Expected format: phaseNN-sessionNN-name"
        exit 1
    fi

    check_spec_system || exit 1

    echo "=============================================="
    echo "SESSION SETUP"
    echo "=============================================="
    echo ""
    echo "Session ID: $session_id"
    echo ""

    # Create directory
    create_session_directory "$session_id"

    # Create placeholders if requested
    if [[ "$create_placeholders" == true ]]; then
        create_placeholder_files "$session_id"
    fi

    # Update state if requested
    if [[ "$update_state_flag" == true ]]; then
        update_state "$session_id"
    fi

    echo ""
    echo "=============================================="
    local session_dir
    session_dir=$(get_session_dir "$session_id")
    log_success "Session setup complete: $session_dir"
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
